# Generated by Django 4.0.6 on 2022-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web3user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='web3user',
            name='is_broker',
        ),
        migrations.RemoveField(
            model_name='web3user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='web3user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='ssn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='web3user',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
